# The point is for the user to remove these configuration records
# one by one as the offenses are removed from the code base.
# Note that changes in the inspected code, or installation of new
# versions of RuboCop, may require this file to be generated again.

# Cop supports --auto-correct.
# Configuration parameters: AlignWith, SupportedStyles, AutoCorrect.
# SupportedStyles: keyword, variable, start_of_line
Lint/EndAlignment:
  Exclude:
    - 'lib/provisioner/provisioner.rb'

Lint/UselessAssignment:
  Exclude:
    - 'lib/provisioner/worker.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'lib/provisioner.rb'
    - 'lib/provisioner/cli.rb'
    - 'lib/provisioner/logging.rb'
    - 'lib/provisioner/plugin/utils.rb'
    - 'lib/provisioner/rest-helper.rb'
    - 'lib/provisioner/tenantmanager.rb'
    - 'lib/provisioner/tenantspec.rb'
    - 'lib/provisioner/worker.rb'
    - 'lib/provisioner/worker/cli.rb'
    - 'lib/provisioner/worker/pluginmanager.rb'
    - 'lib/provisioner/worker/signalhandler.rb'
    - 'lib/provisioner/workerlauncher.rb'

# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Exclude:
    - 'bin/data-uploader.rb'
    - 'lib/provisioner/resourcemanager.rb'
    - 'lib/provisioner/resourcespec.rb'
    - 'lib/provisioner/worker.rb'

# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: snake_case, camelCase
Style/MethodName:
  Exclude:
    - 'lib/provisioner/plugin/automator.rb'
    - 'lib/provisioner/plugin/provider.rb'
    - 'lib/provisioner/worker/pluginmanager.rb'

# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: snake_case, camelCase
Style/VariableName:
  Exclude:
    - 'lib/provisioner/worker.rb'
    - 'lib/provisioner/worker/pluginmanager.rb'

# Manually-added
Style/Dir:
  Enabled: false
Style/Encoding:
  Enabled: false

